version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8500:80"
    volumes:
      - ./bills:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: Obkd,KnA,6Ff6i5r
      MYSQL_DATABASE: facturas_db
    ports:
      - "8357:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Obkd,KnA,6Ff6i5r
    ports:
      - "8081:80"

volumes:
  db_data:
